apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
 replicas: 3
 selector:
   matchLabels:
     app: springboot-app
 template:
   metadata:
     labels:
       app: springboot-app
   spec:                  
     containers:
     - name: springboot-app
       image: vigneshvicky12345/springboot-app:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - port: 8086
      protocol: TCP
      targetPort: 4000
